export const Constants = {
    new: '/New',
    newViewAll: '/new/viewall',
    newFurniture: '/New/Furniture',
    newOutdoor: '/New/outdoor',
    newGifts: '/New/Gifts',
    newDecorAndMirrors: '/New/DECORANDMIRRORS',
    newLighting: '/New/Lighting',
    newPillowsThrow: '/New/PILLOWS&THROWS',
    newRugs: '/New/rugs',
    newKitchenDining: '/new/kitchen&dining',
    newBeddingBath: '/New/BEDDINGANDBATH',
    newOurFavourite: '/New/OURFAVOURITES',

    furniture: '/Furniture',
    furnitureLivingRoom: '/Furniture/livingroom',
    furnitureDining: '/furniture/diningroom',
    furnitureBedroom: '/furniture/bedroom',
    furnitureStorageMediaFurniture: '/furniture/storage&media',
    furnitureOffice: '/furniture/office',
    furnitureBestSeller: '/furniture/bestseller',

    outdoor: '/Outdoor',
    outdoorFurniture: '/outdoor/furniture',
    outdoorAccessories: '/outdoor/Accessories',
    outdoorBestseller: '/outdoor/bestseller',

    decorMirror: '/decor&mirror',
    decorMirrorMirror: '/decor&mirror/mirror',
    decorMirrorHomeAccessories: '/decor&mirror/homeaccessories',
    decorMirrorArtWallDecor: '/decor&mirror/art&walldecor',
    decorMirrorOrganizationHardware: '/decor&mirror/organization&hardware',
    decorMirrorHomeElectronicGames: '/decor&mirror/homeelectronic&games',
    decorMirrorCurtainsCurtainsHardware: '/decor&mirror/Curtains&curtainshardware',
    decorMirrorBestSeller: '/decor&mirror/bestseller',

    lighting: '/lighting',
    lightingViewAll: '/lighting/ViewAll',
    lightingTableLamp: '/lighting/TableLamp',
    lightingFloorLamp: '/lighting/floorlamp',
    lightingPendantLights: '/lighting/pendantlights',
    lightingFlushMounts: '/lighting/flushmounts',
    lightingWallScones: '/lighting/WallScones',
    lightingLightBulbSwitchPlates: '/lighting/lightbulb&switchplates',
    lightingBestSeller: '/lighting/BestSeller',

    pillowThrows: '/pillow&throws',
    pillowThrowsViewAll: '/pillow&throws/ViewAll',
    pillowThrowsPillows: '/pillow&throws/Pillows',
    pillowThrowsPoufs: '/pillow&throws/poufs',
    pillowThrowsThrows: '/pillow&throws/throws',
    pillowThrowsBestSeller: '/pillow&throws/bestSeller',

    rugs: '/rugs',
    rugsViewAll: '/rugs/viewall',
    rugsAreaRugs: '/rugs/Arearugs',
    rugsRunner: '/rugs/runner',
    rugsOneOfAKindRugs: '/rugs/one-of-a-kind-rugs',
    rugsDoormats: '/rugs/doormats',
    rugsKitchenRugs: '/rugs/kitchenRugs',
    rugsOutDoorRugs: '/rugs/outdoorrugs',
    rugsBestSeller: '/rugs/bestseller',

    kitchenDining: '/kitchen&dining',
    kitchenDiningDinnerwareFlatware: '/kitchen&dining/dinnerware&flatware',
    kitchenDiningDinnerwareBar: '/kitchen&dining/dinnerware&bar',
    kitchenDiningServing: '/kitchen&dining/serving',
    kitchenDiningKitchenStorageTools: '/kitchen&dining/kitchenstorage&tools',
    kitchenDiningLinens: '/kitchen&dining/kitchenlinens',
    kitchenDiningBestSeller: '/kitchen&dining/bestsellers',

    beddingBath: '/bedding&bath',
    beddingBathBedding: '/bedding&bath/bedding',
    beddingBathBath: '/bedding&bath/bath',
    beddingBathBestSelllers: '/bedding&bath/bestSeller',

    gifts: '/gifts',
    giftsViewAll: '/gifts/ViewAll',
    giftsBarware: '/gifts/Barware',
    giftsGamesGear: '/gifts/games&gear',
    giftsHostGifts: '/gifts/hostgifts',
    giftsModernKitchen: '/gifts/modernkitchen',
    giftsBathSpa: '/gifts/bath&spa',
    giftsTechOfiice: '/gifts/tech&office',
    giftsUnder25: '/gifts/under25',
    giftsUnder50: '/gifts/under50',
    giftsUnder100: '/gifts/under100',
    giftsSmallGifts: '/gifts/smallgifts',
    giftsThankyouGifts: '/gifts/thankyougifts',
    giftsWedding: '/gifts/Wedding',
    giftsGiftCard: '/gifts/GiftCard',

    saleOffers: '/sales&offer',
    saleOffersViewAll: '/sales&offer/viewall',
    saleOffersUpto20OffMarble: '/sales&offer/upto20offmarble',
    saleOffersUpto30OffSelect: '/sales&offer/upto30offselect',
    saleOffersAllClearance: '/sales&offer/allclearance',
    saleOffersFurniture: '/sales&offer/Furniture',
    saleOffersDecorMirrors: '/sales&offer/decor&mirrors',
    saleOffersLighting: '/sales&offer/lighting',
    saleOffersPillowThrows: '/sales&offer/Pillow&throws',
    saleOffersRugs: '/sales&offer/Rugs',
    saleOffersKitchenDining: '/sales&offer/kitchen&dining',
    saleOffersBeddingBath: '/sales&offer/bedding&bath',
    saleOffersOutDoor: '/sales&offer/Outdoor',
    saleOffersHoliday: '/sales&offer/holiday',
    saleOffersFreeShipping: '/sales&offer/freeshipping',

    rossCassidyColab: '/rosscassidycolab',
    rossCassidyColabRossCassidy: '/rosscassidycolab/rosscassidy',

    karaMannColab: '/karamannColab',

    collaboration: '/collaboration',
    collaborationRossCassidy: '/collaboration/rosscassidy',
    collaborationKaramann: '/collaboration/karamann',
    collaborationJennifer: '/collaboration/jennifer',
    collaborationGQ: '/collaboration/gq',
    collaborationFerrerVintage: '/collaboration/FerrerVintage',
    collaborationGoop: '/collaboration/goop',
    collaborationFredSegal: '/collaboration/fredsegal',
    collaborationMatthewWilliamson: '/collaboration/mathewwilliamson',
    collaborationTheHillSide: '/collaboration/thehill-side',
    collaborationKravitzDesign: '/collaboration/kravitzdesign',
    collaborationNovogratz: '/collaboration/novogratz',
    customer: '/customer'
};
